-- Create sdk_usage table to audit log server SDK calls
-- Tracks org, tenant, user, prompt token usage and metadata

CREATE TABLE IF NOT EXISTS sdk_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id uuid NULL REFERENCES organizations(id) ON DELETE SET NULL,
  tenant_id text NULL,
  user_id text NULL,
  prompt text NULL,
  model text NULL,
  used_tokens integer NULL,
  metadata jsonb NULL
);

-- Helpful indexes for querying usage
CREATE INDEX IF NOT EXISTS idx_sdk_usage_org_id ON sdk_usage(org_id);
CREATE INDEX IF NOT EXISTS idx_sdk_usage_tenant_id ON sdk_usage(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sdk_usage_user_id ON sdk_usage(user_id);
CREATE INDEX IF NOT EXISTS idx_sdk_usage_created_at ON sdk_usage(created_at DESC);

-- Enable Row Level Security
ALTER TABLE sdk_usage ENABLE ROW LEVEL SECURITY;

-- RLS: By default no access
DROP POLICY IF EXISTS "sdk_usage_select" ON sdk_usage;
DROP POLICY IF EXISTS "sdk_usage_insert" ON sdk_usage;

-- SELECT: allow a user to see rows where they are the owner, or
-- they belong to the organization via organization_members, or they are the org owner
CREATE POLICY "sdk_usage_select" ON sdk_usage FOR SELECT USING (
  -- user may view their own rows (user_id equals auth.uid())
  user_id = auth.uid()::text
  OR (
    org_id IS NOT NULL AND (
      -- org owner
      org_id IN (
        SELECT id FROM organizations WHERE owner_id = auth.uid()
      )
      OR
      -- org member
      org_id IN (
        SELECT org_id FROM organization_members WHERE user_id = auth.uid()
      )
    )
  )
);

-- INSERT: allow authenticated users to insert; server validates via API route
CREATE POLICY "sdk_usage_insert" ON sdk_usage FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);

COMMENT ON TABLE sdk_usage IS 'Audit log for server SDK calls (OpenAI/agent runs)';
COMMENT ON COLUMN sdk_usage.org_id IS 'Organization making the call';
COMMENT ON COLUMN sdk_usage.tenant_id IS 'Customer tenant identifier provided by the caller';
COMMENT ON COLUMN sdk_usage.user_id IS 'End user identifier provided by the caller';
COMMENT ON COLUMN sdk_usage.used_tokens IS 'Tokens used as reported by the model/provider when available';

