services:
  app_db:
    image: pgvector/pgvector:pg16
    container_name: sql_agent_db
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./titanic.sql:/docker-entrypoint-initdb.d/init.sql
      - app_db_data:/var/lib/postgresql/data

  demo_db:
    image: postgres:16
    container_name: querypanel_demo_db
    environment:
      POSTGRES_DB: pg_demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    ports:
      - "5433:5432"
    volumes:
      - demo_db_data:/var/lib/postgresql/data

  clickhouse_demo:
    image: clickhouse/clickhouse-server:latest
    container_name: querypanel_clickhouse_demo
    environment:
      CLICKHOUSE_DB: demo
      CLICKHOUSE_USER: demo
      CLICKHOUSE_PASSWORD: demo123
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  app_db_data:
  demo_db_data:
  clickhouse_data:
